session:
  name: base
  windows:
  - name: ide
    layout: null
    panes:
    - cwd: .
      command:
      - source ./.venv/bin/activate.fish
      - nvim
  - name: run
    layout: main-horizontal
    panes:
    - cwd: .
      command:
      - source .venv/bin/activate.fish
    - cwd: ./src
      command:
      - source .venv/bin/activate.fish
