# Disable the default prompt line break
add_newline = false

# Use a simple, minimal format
format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$character
"""

# Username (only show if not default)
[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style) "
show_always = true  # Only show if not default user

# Hostname (only show if SSH)
[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "bold dimmed"

# Directory (truncated to 3 parent dirs)
[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "
style = "bold blue"

# Git Branch (only shows in a repo)
[git_branch]
format = "[$branch]($style) "
style = "bold purple"

# Prompt character (❯ for user, # for root)
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold purple)"
