add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$character\
"""
[custom.logo]
command = "echo 󱗆 "
when = "true"
style = "bold #ff003c"

[username]
style_user = "bold #ff003c"  # bright blood red
style_root = "bold #ff003c"
format = "[󱗆 $symbol$user]($style) "
show_always = true

[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "bold #00bfff"  # bright azure blue

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "
style = "bold #1e90ff"  # DodgerBlue (bright and readable)
read_only = " "

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold white"
symbol = " "

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "bold #ff1493"  # DeepPink for a vivid, stylish contrast
conflicted = "="
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"

[character]
success_symbol = "[❯](bold #ffffff)"   # bright white
error_symbol = "[❯](bold #ff003c)"     # bright red
vicmd_symbol = "[❮](bold #9b30ff)"     # bright violet

