add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character\
"""

[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style) "
show_always = true  # Always show (like your bash config)

[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "bold dimmed"

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "
style = "bold #5f87ff"
read_only = " "

[git_branch]
# format = "[$branch]($style) "
format = "[$symbol$branch]($style) "
style = "bold"
symbol = " "

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "bold yellow"
conflicted = "="
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold purple)"# Time - disabled by default but can be enabled

[time]
disabled = false  # Enable if you want timestamp
format = "[$time]($style) "
time_format = "%T"  # 24-hour format
