[global]
default_target_base = "backups"
default_rsync_flags = ["-a", "--delete", "--exclude=.venv/"]

[drives.aura]
uuid = "4051FBFC5BE73E7F"

[drives.towa]
uuid = "2370-01A2"

[drives.bloodraven]
uuid = "0ba9273e-bf4e-4aa0-8feb-0b495e1da0b8"

[[jobs.backup]]
name = "general"
sources = ["/home/holo/dotfiles", "/home/holo/projects", "/home/holo/desktop", "/home/holo/pictures", "/home/holo/videos", "/home/holo/downloads", "/home/holo/documents", "/home/holo/music", "/home/holo/.codex"]
drives = ["aura", "towa", "bloodraven"]

[[jobs.custom]]
name = "share"
sources = ["/home/holo/share/"]
drives = ["aura", "towa", "bloodraven"]
