[general]
rsync_flags = "-avh --delete"
pcname = "holo"
tgbase = "pc_backups"

[[drives]]
label = "bloodraven"
uuid = "3B479ACA6574FECE"

[[drives]]
label = "aura"
uuid = "4051FBFC5BE73E7F"

[[default]]
name = "general"
sources = ["/home/leogabac/shorui", "/home/leogabac/Desktop", "/home/leogabac/Pictures", "/home/leogabac/Videos", "/home/leogabac/Downloads", "/home/leogabac/Documents"]

[[custom]]
name = "share"
label = "bloodraven"
uuid = "3B479ACA6574FECE"
sources = ["/home/leogabac/share"]
tgbase = ""
rsync_flags = "-avh --delete"

[[custom]]
name = "test"
label = "jail bird"
uuid = "3C031AE62823D49F"
sources = ["/home/leogabac/share"]
tgbase = ""
rsync_flags = "-avh --delete"

